// --- Global State & Storage ---
const STORAGE_KEYS = { CART: 'mob_cart_v10' };

let products = [];
let cart = JSON.parse(localStorage.getItem(STORAGE_KEYS.CART)) || [];

const productGrid = document.getElementById('productGrid');
const cartCountEl = document.getElementById('cartCount');

// --- 1. Load Products from Decap CMS ---
async function loadProducts() {
  try {
    // Fetches the JSON file generated by Decap CMS
    const res = await fetch('/data/products.json');
    const data = await res.json();
    products = data.items || [];
    renderProducts();
  } catch (err) {
    console.error("No products found or error loading CMS data:", err);
    productGrid.innerHTML = '<p style="text-align:center; color: var(--text-muted);">Loading products... (If you just deployed, make sure you have added products in the /admin panel!)</p>';
  }
}

// --- 2. UI Helpers (Toasts & Modals) ---
function showToast(msg, isSuccess = true) {
  const container = document.getElementById('toastContainer');
  const toast = document.createElement('div');
  toast.className = 'toast';
  toast.style.borderLeftColor = isSuccess ? 'var(--success)' : 'var(--danger)';
  toast.innerHTML = isSuccess ? `✅ ${msg}` : `❌ ${msg}`;
  container.appendChild(toast);
  setTimeout(() => { toast.classList.add('fadeOut'); setTimeout(() => toast.remove(), 400); }, 3000);
}

function openModal(modal){ modal.classList.remove('hidden'); }
function closeModal(modal){ modal.classList.add('hidden'); }

// Close buttons for Modals
document.querySelectorAll('.close').forEach(b => b.addEventListener('click', e => { 
  const t = e.target.dataset.target; 
  if(t) closeModal(document.getElementById(t)); else closeModal(e.target.closest('.modal')); 
}));

// Open Cart
document.getElementById('openCartBtn').addEventListener('click', () => { 
  renderCart(); 
  openModal(document.getElementById('cartModal')); 
});


// --- 3. Render Products (With Stock & Unit Logic) ---
function renderProducts(){
  productGrid.innerHTML = '';
  products.forEach(p => {
    const div = document.createElement('div');
    div.className = 'card product-card shadow-card';
    
    // Determine fractional steps based on unit
    const stepVal = (p.unit === 'kg' || p.unit === 'liter' || p.unit === 'g') ? '0.05' : '1';
    
    // Stock Status Logic
    const currentStock = p.stock_status || "In Stock";
    const isOutOfStock = currentStock === "Out of Stock";
    
    // Visuals based on stock
    const badgeHtml = isOutOfStock 
      ? `<span class="badge badge-danger" style="margin-bottom: 10px; display: inline-block;">Out of Stock</span>` 
      : ``; 
      
    const disabledAttr = isOutOfStock ? 'disabled' : '';
    const btnClass = isOutOfStock ? 'btn-light' : 'btn-primary';
    const btnText = isOutOfStock ? 'Currently Unavailable' : 'Add to Cart';
    const imgOpacity = isOutOfStock ? 'opacity: 0.5; filter: grayscale(50%);' : '';

    div.innerHTML = `
      <img src="${p.img || 'https://via.placeholder.com/400x300?text=No+Image'}" alt="${p.name}" style="${imgOpacity}">
      ${badgeHtml}
      <h4 style="${isOutOfStock ? 'color: var(--text-muted);' : ''}">${p.name}</h4>
      <p class="price" style="${isOutOfStock ? 'color: var(--text-muted);' : ''}">₹${p.price.toFixed(2)} <span style="font-size:0.85rem;">/ ${p.unit}</span></p>
      
      <div style="display:flex; gap:10px; margin: 10px 0 15px; justify-content:center;">
        <input type="number" id="qty-${p.id}" value="1" min="0.05" step="${stepVal}" style="width:80px; padding:8px; text-align:center; font-weight:bold;" ${disabledAttr}>
        <span style="font-weight:700; align-self:center; ${isOutOfStock ? 'color: var(--text-muted);' : ''}">${p.unit}</span>
      </div>
      
      <button class="${btnClass}" onclick="addToCart('${p.id}')" ${disabledAttr}>${btnText}</button>
    `;
    productGrid.appendChild(div);
  });
}

// --- 4. Cart Logic ---
window.addToCart = function(productId){
  const prod = products.find(p=>p.id===productId);
  
  // Security check: Prevent adding out of stock items
  if(!prod || prod.stock_status === "Out of Stock") {
    showToast('This item is currently out of stock.', false);
    return;
  }
  
  const qtyToAdd = parseFloat(document.getElementById(`qty-${productId}`).value) || 1;
  const existing = cart.find(c=>c.id===productId);
  
  if(existing) existing.qty += qtyToAdd;
  else cart.push({ id: productId, name: prod.name, price: prod.price, unit: prod.unit, qty: qtyToAdd, img: prod.img });
  
  localStorage.setItem(STORAGE_KEYS.CART, JSON.stringify(cart));
  updateCartCount();
  showToast(`${qtyToAdd} ${prod.unit} of ${prod.name} added`);
}

function updateCartCount(){ 
  cartCountEl.textContent = cart.length; 
}

function renderCart(){
  const container = document.getElementById('cartItems'); container.innerHTML = '';
  if(cart.length===0){ container.innerHTML = '<p style="text-align:center; padding: 20px;">Your cart is empty</p>'; updateTotals(); return; }
  
  cart.forEach(item => {
    const row = document.createElement('div'); row.className = 'card shadow-card';
    row.style.display = 'flex'; row.style.alignItems = 'center'; row.style.gap = '15px'; row.style.marginBottom = '12px'; row.style.padding = '10px';
    
    const stepVal = (item.unit === 'kg' || item.unit === 'liter' || item.unit === 'g') ? '0.05' : '1';
    
    row.innerHTML = `
      <img src="${item.img || 'https://via.placeholder.com/80'}" style="width:60px; height:60px; border-radius:8px; object-fit:cover;">
      <div style="flex:1;">
        <strong style="font-size: 1rem;">${item.name}</strong><br>
        <span style="font-size:0.85rem; color: var(--text-muted);">₹${item.price.toFixed(2)} / ${item.unit}</span>
        <div style="color:var(--primary); font-weight:bold; font-size: 1.1rem;">₹${(item.price * item.qty).toFixed(2)}</div>
      </div>
      <div style="display:flex; flex-direction:column; align-items:center; gap:5px;">
        <input type="number" min="0.05" step="${stepVal}" value="${item.qty}" style="width:70px; padding:6px; text-align:center; font-weight: bold; border-radius: 6px; border: 1px solid #cbd5e1;" onchange="updateQty('${item.id}', this.value)">
        <span style="font-size:0.75rem; font-weight:bold; color:var(--text-muted); text-transform:uppercase;">${item.unit}</span>
      </div>
      <button class="btn-danger" style="padding:8px 12px; width: auto;" onclick="removeFromCart('${item.id}')">✕</button>
    `;
    container.appendChild(row);
  });
  updateTotals();
}

window.updateQty = (id, val) => {
  const item = cart.find(c => c.id === id);
  if(item) { item.qty = Math.max(0.01, parseFloat(val)||1); localStorage.setItem(STORAGE_KEYS.CART, JSON.stringify(cart)); renderCart(); }
};

window.removeFromCart = (id) => { 
  cart = cart.filter(c=>c.id!==id); localStorage.setItem(STORAGE_KEYS.CART, JSON.stringify(cart)); renderCart(); updateCartCount(); 
};

function updateTotals(){
  const subtotal = cart.reduce((s,i)=>s + (i.price * i.qty), 0);
  const tax = subtotal * 0.05; 
  const total = subtotal + tax;
  
  document.getElementById('subtotal').textContent = subtotal.toFixed(2);
  document.getElementById('tax').textContent = tax.toFixed(2);
  document.getElementById('total').textContent = total.toFixed(2);

  // Update Hidden Inputs for Netlify Forms to capture what the user bought
  const cartSummaryString = cart.map(item => `${item.qty} ${item.unit} x ${item.name} (₹${(item.price * item.qty).toFixed(2)})`).join('\n');
  const hiddenCartData = document.getElementById('hiddenCartData');
  const hiddenOrderTotal = document.getElementById('hiddenOrderTotal');
  
  if(hiddenCartData) hiddenCartData.value = cartSummaryString;
  if(hiddenOrderTotal) hiddenOrderTotal.value = `₹${total.toFixed(2)} (Includes ₹${tax.toFixed(2)} tax)`;

  // Dynamic UPI deep link update
  const dynamicLinkBtn = document.getElementById('dynamicUpiLink');
  const paymentSection = document.getElementById('dynamicPaymentSection');
  if (total > 0 && dynamicLinkBtn && paymentSection) {
    dynamicLinkBtn.href = `upi://pay?pa=8918636763@yapl&pn=Mobarok%20Online%20Service&am=${total.toFixed(2)}&cu=INR`;
    document.getElementById('payAmountTxt').textContent = total.toFixed(2);
    paymentSection.style.display = 'block';
  } else if (paymentSection) {
    paymentSection.style.display = 'none';
  }
}


// --- 5. Netlify Form Submissions (AJAX without page reload) ---

// Helper function to submit form data to Netlify silently
function submitToNetlify(formElement) {
  // FormData handles text inputs AND file uploads perfectly
  return fetch('/', {
    method: 'POST',
    body: new FormData(formElement)
  });
}

// Checkout Orders
document.getElementById('checkoutForm').addEventListener('submit', function(e){
  e.preventDefault();
  if(cart.length===0){ showToast('Your cart is empty', false); return; }
  
  submitToNetlify(this).then(() => {
    cart = []; localStorage.setItem(STORAGE_KEYS.CART, JSON.stringify(cart)); updateCartCount();
    closeModal(document.getElementById('cartModal'));
    showToast('Order placed! We have received your request.');
    this.reset();
  }).catch(error => {
    console.error(error);
    showToast('Error placing order. Please try again.', false);
  });
});

// Mobile Recharges
document.getElementById('rechargeForm').addEventListener('submit', function(e){
  e.preventDefault();
  submitToNetlify(this).then(() => {
    showToast('Recharge request sent successfully!');
    this.reset();
  }).catch(error => {
    console.error(error);
    showToast('Error sending request.', false);
  });
});

// Print Document Uploads
document.getElementById('uploadForm').addEventListener('submit', function(e){
  e.preventDefault();
  submitToNetlify(this).then(() => {
    showToast('Document securely uploaded to server!');
    this.reset();
  }).catch(error => {
    console.error(error);
    showToast('Error uploading document.', false);
  });
});

// --- 6. Initialization ---
loadProducts();
updateCartCount();